---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-rest-api
  labels:
    app: px-mongo-rest
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mongodb-rest-api
    tier: compute
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-rest-api
  labels:
    app: px-mongo-rest
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb-rest-api
        tier: compute
    spec:
      containers:
        - image: fmrtl73/px-mongo-rest
          imagePullPolicy: Always
          name: mongodb-rest-api
          env:
            - name: spring_active_profile
              value: prod
          env:
            - name: mongodb_svc_name
              value: px-mongodb
          ports:
            - containerPort: 8080
